render_mode: center
basedir: ./log
filter_rays: false
expname: lego_v6_sigmoid_5lnorm_samp2_mean
datadir: /optane/nerf_datasets
render_only: false
render_train: false
render_test: true
render_path: false
add_timestamp: false
nSamples: 1000000.0
N_vis: 5
vis_every: 5000
progress_refresh_rate: 10
rm_weight_mask_thre: 0.0001
step_ratio: 0.5
ckpt: null
lr_decay_iters: -1
lr_decay_target_ratio: 0.1
lr_upsample_reset: 1
fp16: false
n_bg_iters: 1000
save_often: false
fixed_bg: null
dataset:
  scenedir: nerf_synthetic/lego
  dataset_name: blender
  downsample_train: 1
  downsample_test: 1
  ndc_ray: false
  near_far:
  - 2.5
  - 7
model:
  arch:
    _target_: models.tensor_nerf.TensorNeRF
    _partial_: true
    rayMarch_weight_thres: 0.0001
    recur_weight_thres: 0.0001
    max_recurs: 1
    roughness_rays: 50
    max_recur_rays: 5
    infinity_border: false
    use_diffuse: true
    appdim_noise_std: 0.0
    world_bounces: 2048000
    max_normal_similarity: 1
    cold_start_bg_iters: 500
    attach_normal_iter: 0
    transmittance_thres: 1.0
    back_clip: 0.0
    percent_bright: 0.1
    transmit_iter: 1000
    normalize_brdf: false
    detach_inter: true
    selector:
      _target_: modules.pt_selectors.TopNWeight
      _partial_: true
      max_selected: 25000000
      weight_thres: 0.001
    tonemap:
      _target_: models.tonemap.SRGBTonemap
    sampler:
      _target_: samplers.continuous_alphagrid.ContinuousAlphagrid
      _partial_: true
      multiplier: 2
      shrink_iters:
      - 2000
      - 4000
      dynamic_batchsize: false
      sample_mode: multi_jitter
      test_sample_mode: midpoint
      threshold: 5.0e-05
      grid_size: 128
      bound: 1.5
    brdf_sampler:
      _target_: models.brdf.GGXSampler
      _partial_: true
      min_roughness: 0.0
    brdf:
      _target_: models.brdf.MLPBRDF
      _partial_: true
      feape: 0
      dotpe: -1
      h_encoder:
        _target_: models.render_modules.PE
        max_degree: 2
      d_encoder:
        _target_: models.render_modules.PE
        max_degree: 2
      featureC: 64
      num_layers: 4
      activation: sigmoid
      mul_ggx: false
      mix_diffuse: false
      use_roughness: true
      detach_roughness: false
      lr: 1.0e-05
    bg_module:
      _target_: models.bg_modules.HierarchicalCubeMap
      bg_resolution: 1024
      mipbias: -1
      num_levels: 1
      activation: exp
      power: 2
      stds: []
      lr: 0.4
      init_val: -1
      mul_lr: 0.1
      brightness_lr: 0.01
      betas:
      - 0.9
      - 0.999
      mul_betas:
      - 0.9
      - 0.99
      mipbias_lr: 0.0001
      mipnoise: 0.5
    diffuse_module:
      _partial_: true
      _target_: models.render_modules.MLPDiffuse
      pospe: -1
      feape: 2
      featureC: 128
      num_layers: 3
      lr: 0.0001
      tint_offset: 2
    normal_module:
      _partial_: true
      _target_: models.render_modules.MLPNormal
      lr: 0.001
      pospe: 12
      feape: 0
      featureC: 128
      num_layers: 5
      size_multi: 0.0025
    rf:
      _partial_: true
      _target_: fields.tensoRF.TensorVMSplit
      distance_scale: 25
      density_n_comp: 16
      appearance_n_comp: 16
      app_dim: 16
      step_ratio: 0.5
      density_res_multi: 1
      contract_space: false
      smoothing: 0.5
      activation: softplus_shift
      dbasis: false
      init_mode: randplane
      interp_mode: bilinear
      density_shift: -10
      N_voxel_init: 2097156
      N_voxel_final: 27000000
      upsamp_list:
      - 2000
      - 3000
      - 4000
      - 5500
      - 7000
      lr: 0.02
      lr_net: 0.001
      num_pretrain: 0
  params:
    L1_weight_inital: 8.0e-05
    L1_weight_rest: 4.0e-05
    TV_weight_density: 0.0
    TV_weight_app: 0.0
    normal_lambda: 0.003
    diffuse_lambda: 0
    backwards_rays_lambda: 0.05
    floater_lambda: 0.001
    visibility_lambda: 0
    charbonier_eps: 0.001
    ortho_weight: 0
    N_visibility_rays: 128
    n_iters: 30000
    charbonier_loss: false
    start_density: 0.001
    lr_init: 0.02
    batch_size: 2048
field:
  _partial_: true
  _target_: fields.tensoRF.TensorVMSplit
  distance_scale: 25
  density_n_comp: 16
  appearance_n_comp: 16
  app_dim: 16
  step_ratio: 0.5
  density_res_multi: 1
  contract_space: false
  smoothing: 0.5
  activation: softplus_shift
  dbasis: false
  init_mode: randplane
  interp_mode: bilinear
  density_shift: -10
  N_voxel_init: 2097156
  N_voxel_final: 27000000
  upsamp_list:
  - 2000
  - 3000
  - 4000
  - 5500
  - 7000
  lr: 0.02
  lr_net: 0.001
  num_pretrain: 0
