arch:
  _target_: models.tensor_nerf.TensorNeRF
  _partial_: True

  density_shift: -10
  alphaMask_thres: 0.0001
  rayMarch_weight_thres: 0.0001
  nEnvSamples: 0
  fea2denseAct: 'softplus_shift'
  # fea2denseAct: 'relu_shift'
  max_recurs: 2
  roughness_rays: 100
  infinity_border: False
  enable_alpha_mask: false
  appdim_noise_std: 0.0
  world_bounces: 0
  max_normal_similarity: 1.0
  max_floater_loss: 1
  selector:
    # _target_: models.modules.selectors.Surface
    _target_: modules.pt_selectors.TopNWeight
    max_selected: 25000
    weight_thres: 1e-3
    eps: 1e-1

  sampler:
    _target_: samplers.alphagrid.AlphaGridSampler
    enable_alpha_mask: False
    nEnvSamples: 0
    near_far: [2, 4]
    # _target_: samplers.raymarch.Raymarcher

  rf:
    _partial_: True
    _target_: fields.tensoRF.TensorVMSplit
    density_n_comp: 16
    appearance_n_comp: 24
    app_dim: 24
    step_ratio: 0.5
    density_res_multi: 1
    contract_space: False
    smoothing: 1.5

    N_voxel_init: 2097156 # 128**3
    N_voxel_final: 27000000 # 300**3
    # N_voxel_init: 27000000 # 128**3
    # N_voxel_final: 134217728 # 300**3
    upsamp_list: [3000,4000,5500,7000]

  # brdf_sampler:
  #   _target_: modules.brightness_sampler.BrightnessSampler
  #   _partial_: True
  #   n: 20
  #   decay: 0.99
  #   sampler:
  #     _target_: models.brdf.GGXSampler
  #     _partial_: True
  brdf_sampler:
    _target_: models.brdf.GGXSampler
    _partial_: True

  tonemap:
    # _target_: models.tonemap.HDRTonemap
    # _target_: models.tonemap.LinearTonemap
    _target_: models.tonemap.SRGBTonemap

  # brdf:
  #   _target_: models.brdf.PBR
  #   _partial_: True

  brdf:
    _target_: models.brdf.MLPBRDF
    # _target_: models.brdf.LightTinter
    _partial_: True
    # pbr: True

    # v_encoder:
    #   _target_: models.ish.ListISH
    #   degs: [0,1,2,4]
    # l_encoder:
    #   _target_: models.ish.ListISH
    #   degs: [0,1,2,4]

    # v_encoder:
    #   _target_: models.ish.ListISH
    #   degs: [0,1,2,4,8]
    # l_encoder:
    #   _target_: models.ish.ListISH
    #   degs: [0,1,2,4,8]

    # v_encoder:
    #   _target_: models.ish.ListISH
    #   degs: [0,1,2,4,8,16]
    # l_encoder:
    #   _target_: models.ish.ListISH
    #   degs: [0,1,2,4,8,16]
    num_layers: 5
    feape: 0
    featureC: 128
    activation: 'softplus'
    mul_ggx: True
    use_roughness: true
    detach_roughness: false
    lr: 1e-3

  bg_module:
    _target_: models.bg_modules.HierarchicalCubeMap
    bg_resolution: 1024
    num_levels: 1
    activation: 'softplus'
    power: 2
    stds: []
    # lr: 0.30
    # lr: 0.05
    lr: 0.10

  diffuse_module:
    _partial_: True
    _target_: models.render_modules.MLPDiffuse
    pospe: 0
    feape: 2
    featureC: 128
    num_layers: 3
    lr: 1e-4

  normal_module:
    _partial_: True
    _target_: models.render_modules.MLPNormal
    lr: 1e-3
    pospe: 16
    feape: 2
    featureC: 128
    num_layers: 3

params:
  lambda_start: 0.0
  lambda_end: 0.0
  smoothing_list: [10000, 15000, 20000]

  # bounce_n_list: [100, 1000, 10000, 20000]
  # bounce_iter_list: [9000, 12000, 14000]

  bounce_n_list: [0, 100000]
  # bounce_iter_list: [4500]
  bounce_iter_list: [0]

  num_bw_iters: 0

  #upsamp_list: [2000,3000,4000,5500,7000]
  #uplambda_list: [7000, 12000, 17000, 21000]
  #uplambda_list: [7000, 12000, 17000]
  uplambda_list: [7000, 10000, 12000]
  update_AlphaMask_list: [8000]
  L1_weight_inital: 0
  L1_weight_rest: 4e-5

  TV_weight_density: 0.0
  TV_weight_app: 0.0
  normal_lambda: 3e-4
  diffuse_lambda: 0
  backwards_rays_lambda: 0.1
  floater_lambda: 1e-5
  charbonier_eps: 1e-3
  ortho_weight: 0

  envmap_train_start: 20
  # num_rays_per_envmap: 512
  num_rays_per_envmap: 64
  num_env_train_iters: 0
  n_iters: 30000
  charbonier_loss: false
  start_density: 1e-2
  lr_init: 0.02
