_target_: models.tensor_nerf.TensorNeRF
_partial_: True

density_shift: -10
alphaMask_thres: 0.00001
distance_scale: 25
rayMarch_weight_thres: 0.0001
nEnvSamples: 0
fea2denseAct: 'softplus_shift'
# fea2denseAct: 'relu_shift'
max_recurs: 2
infinity_border: False
enable_alpha_mask: false

rf:
  _partial_: True
  _target_: models.tensoRF.TensorVMSplit
  density_n_comp: 16
  appearance_n_comp: 48
  app_dim: 48
  step_ratio: 0.5
  density_res_multi: 1
  contract_space: False
  # num_levels: 1
  hier_sizes: [1]

bg_module:
  _target_: models.render_modules.BackgroundRender
  bg_rank: 3
  num_layers: 0
  # view_encoder:
  #   _target_: models.ish.ISH
  #   max_degree: 6
  # bg_resolution: [4096, 2048]
  bg_resolution: 256

diffuse_module:
  _partial_: True
  _target_: models.render_modules.MLPDiffuse
  pospe: 0
  feape: 2
  view_encoder:
    _target_: models.ish.ISH
    max_degree: 6
  featureC: 128
  num_layers: 0

# ref_module:
#   _partial_: True
#   _target_: models.render_modules.MLPRender_FP
#   feape: 2
#   # view_encoder:
#   #   _target_: models.ish.ISH
#   #   max_degree: 6
#   ref_encoder:
#     _target_: models.ish.RandISH
#     # rand_n: 8
#     rand_n: 64
#     std: 7
#   featureC: 128
#   num_layers: 3

normal_module:
  _partial_: True
  _target_: models.render_modules.MLPNormal
  pospe: 0
  feape: 2
  featureC: 128
  num_layers: 1


