arch:
  _target_: models.tensor_nerf.TensorNeRF
  _partial_: True

  rayMarch_weight_thres: 1e-4
  recur_weight_thres: 1e-4
  lr_scale: 1
  infinity_border: False
  eval_batch_size: 4096

  anoise: 0.0
  anoise_decay: 0.9995

  bg_noise: 0.0
  bg_noise_decay: 0.999
  rough_light: False

  max_brdf_rays: [3194304]
  cold_start_bg_iters: 0
  detach_N_iters: 5000
  normalize_brdf: False
  use_predicted_normals: True
  orient_world_normals: False
  diffuse_dropout: 0

  transmittance_thres: 1.0
  percent_bright: 0.1

  detach_inter: True
  selector:
    _target_: modules.pt_selectors.Selector
    _partial_: True
    max_selected: 25000000
    weight_thres: 1e-3

  # bright_sampler:
  #   _target_: modules.bright_sampler.BrightnessImportanceSampler
  #   _partial_: True
  #   scale: 10
  #   update_freq: 50

  tonemap:
    # _target_: models.tonemap.HDRTonemap
    # _target_: models.tonemap.LinearTonemap
    _target_: models.tonemap.SRGBTonemap

  sampler:
    _target_: samplers.continuous_alphagrid.ContinuousAlphagrid
    _partial_: True
    multiplier: 2
    shrink_iters: []
    dynamic_batchsize: True
    # sample_mode: multi_jitter
    sample_mode: single_jitter
    test_sample_mode: midpoint
    # threshold: 5e-5
    threshold: 1e-4
    grid_size: 256
    max_samples: 200000
    conv: 10
    bound: 1.5

    # _target_: samplers.alphagrid.AlphaGridSampler
    # _partial_: True
    # enable_alpha_mask: False
    # nEnvSamples: 0
    # update_list: [4000, 8000]
    # multiplier: 1
    # threshold: 0.0001

    # _target_: samplers.raymarch.Raymarcher
    # _partial_: True
    # max_samples: 100000
    # grid_size: 256
    # max_steps: 1024

  brdf_sampler:
    _target_: models.brdf.GGXSampler
    # _target_: models.brdf.CosineLobeSampler
    # _target_: models.brdf.BeckmannSampler
    _partial_: True

  brdf:
    _target_: models.brdf.MLPBRDF
    _partial_: True
    # pbr: True

    # v_encoder:
    #   _target_: models.ish.ListISH
    #   degs: [0,1,2,4]
    # l_encoder:
    #   _target_: models.ish.ListISH
    #   degs: [0,1,2,4]
    # num_layers: 4
    # feape: 0
    # featureC: 128
    mul_LdotN: True
    feape: 0
    dotpe: -1
    h_encoder:
      _target_: models.render_modules.PE
      max_degree: 2
    d_encoder:
      _target_: models.render_modules.PE
      max_degree: 2
    # h_encoder:
    #   _target_: models.ish.ListISH
    #   degs: [0,1,2,4]
    # d_encoder:
    #   _target_: models.ish.ListISH
    #   degs: [0,1,2,4]
    hidden_w: 64
    num_layers: 4
    initializer: 'kaiming'

    # num_layers: 4
    # dotpe: 6
    # featureC: 128
    # activation: 'sigexp'
    bias: 3
    activation: 'sigmoid'
    # activation: 'sigmoid'
    lr: 1e-3

  bg_module:
    _target_: models.bg_modules.HierarchicalCubeMap
    bg_resolution: 512
    mipbias: 0
    num_levels: 1
    TV_max_scale: 1
    activation: 'exp'
    power: 2
    stds: []
    lr: 0.05
    init_val: 0
    mul_lr: 0
    brightness_lr: 0
    betas: [0.0, 0.0]
    mul_betas: [0.9, 0.99]
    mipbias_lr: 1e-4
    mipnoise: 0.0

  # diffuse_module:
  #   _partial_: True
  #   _target_: models.render_modules.MLPDiffuse
  #   pospe: -1
  #   feape: 0
  #   # pospe: 12
  #   # feape: 0
  #   # view_encoder:
  #   #   _target_: models.render_modules.PE
  #   #   max_degree: 2
  #   hidden_w: 64
  #   num_layers: 3
  #   initializer: 'kaiming'
  #   lr: 1e-3
  #   tint_offset: -1.1
  #   diffuse_offset: -1.1
  #   roughness_offset: 3
  #   # allocation: 7

  diffuse_module:
    _partial_: True
    _target_: models.render_modules.HydraMLPDiffuse
    pospe: -1
    feape: 0
    # pospe: 12
    # feape: 0
    # view_encoder:
    #   _target_: models.render_modules.PE
    #   max_degree: 2
    hidden_w: 64
    num_layers: 1
    initializer: 'kaiming'
    lr: 1e-3
    tint_offset: -1.1
    diffuse_offset: -1.1
    roughness_offset: 3
    # allocation: 7

  normal_module:
    _partial_: True
    _target_: models.render_modules.MLPNormal
    lr: 1e-3
    # pospe: -1
    # feape: 2
    # pospe: 0
    pospe: 0
    feape: 0

    hidden_w: 64
    num_layers: 3
    initializer: 'kaiming_fanout'
    size_multi: 2.5e-3
    # allocation: 3
    offset_geometry: False

  rf: 'placeholder'

params:
  L1_weight_inital: 0
  L1_weight_rest: 0
  clip_grad: 100
  eps: 1e-8
  betas: [0.9, 0.999]

  TV_weight_density: 0.0
  TV_weight_app: 0.0
  TV_weight_bg: 0
  envmap_lambda: 5e-5
  pred_lambda: 2e-4
  final_pred_lambda: Null
  diffuse_lambda: 1e-8
  ori_lambda: 0.01
  final_ori_lambda: Null
  brdf_lambda: 0
  
  distortion_lambda: 0 # 1e-3
  visibility_lambda: 0
  # distortion_lambda: 0.00001
  charbonier_eps: 1e-3
  ortho_weight: 0
  N_visibility_rays: 128

  n_iters: 30000
  charbonier_loss: false
  start_density: 1e-2
  lr_init: 0.02
  batch_size: 4096
  lr: Null

