arch:
  _target_: modules.tensor_nerf.TensorNeRF
  _partial_: True

  recur_alpha_thres: 1e-3
  lr_scale: 1
  infinity_border: False
  eval_batch_size: 10240
  recur_stepmul: 0.5

  bg_noise: 0.0
  bg_noise_decay: 0.999

  use_predicted_normals: False
  orient_world_normals: True
  align_pred_norms: True
  detach_inter: False
  geonorm_iters: -1
  geonorm_interp_iters: 1000
  contraction: "AABB"

  tonemap:
    # _target_: modules.tonemap.HDRTonemap
    # _target_: modules.tonemap.LinearTonemap
    _target_: modules.tonemap.SRGBTonemap

  sampler:
    _target_: samplers.nerf_acc.NerfAccSampler
    _partial_: True
    grid_size: 128
    update_freq: 16
    multiplier: 2
    test_multiplier: 1
    shrink_iters: []
    ema_decay: 0.95
    occ_thre: 0.01
    warmup_iters: 256
    alpha_thres: 0
    max_samples: 250000

  normal_module:
    _partial_: True
    _target_: modules.render_modules.MLPNormal
    lr: 1e-3
    # pospe: -1
    # feape: 2
    # pospe: 0
    pospe: -1
    feape: 0

    hidden_w: 64
    num_layers: 3
    initializer: 'kaiming'
    size_multi: 2.5e-3
    # allocation: 3
    offset_geometry: False

  model:
    _partial_: True
    _target_: models.dual_model.DualModel
    warmup_iters: 5000
    alternating: False
    # model1: 
    #   _partial_: True
    #   _target_: models.tensorf.TensoRF
    #   diffuse_module:
    #     _partial_: True
    #     _target_: modules.render_modules.MLPRender_Fea
    #     featureC: 128
    #     viewpe: 2
    #     feape: 2
    model1:
      _partial_: True
      _target_: models.refnerf.RefNeRF
      anoise: 0.1
      detach_N_iters: 500

      ref_module:
        _partial_: True
        _target_: modules.render_modules.MLPRender_FP
        feape: 0
        lr: 1e-4
        # view_encoder:
        #   _target_: models.ish.FullISH
        #   max_degree: 4
        # ref_encoder:
        #   _target_: models.ish.ListISH
        #   degs: [0,1,2,4,8,16]
        ref_encoder:
          _target_: modules.refsh.RefSH
          deg_view: 5
        # ref_encoder:
        #   _target_: models.render_modules.PE
        #   max_degree: 4
        # ref_encoder:
        #   _target_: models.ish.ISH
        #   max_degree: 6
        # ref_encoder:
        #   _target_: models.ish.RandISH
        #   rand_n: 64
        #   std: 5
        # activation: 'softplus'
        activation: 'sigmoid'
        initializer: 'kaiming'
        hidden_w: 256
        num_layers: 8
        skip: 4
        offset: 0

      diffuse_module:
        _partial_: True
        _target_: modules.render_modules.RandHydraMLPDiffuse
        pospe: -1
        feape: 0
        # pospe: 12
        # feape: 0
        # view_encoder:
        #   _target_: modules.render_modules.PE
        #   max_degree: 2
        roughness_view_encoder: NULL
          # _target_: modules.render_modules.PE
          # max_degree: 2
        roughness_cfg:
          hidden_w: 64
          num_layers: 1
          # num_layers: 2
        hidden_w: 64
        num_layers: 1
        initializer: 'xavier_sigmoid'
        lr: 1e-3
        start_roughness: 0.35
        tint_bias: -1.1
        diffuse_bias: -0.619
        diffuse_mul: 1.5
        roughness_bias: -1
        # allocation: 7
    model2: 
      _partial_: True
      _target_: models.microfacet.Microfacet
      percent_bright: 0.0
      max_brdf_rays: [450000, 450000]
      target_num_samples: [800000]
      max_retrace_rays: [10000]
      # max_brdf_rays: [450000]
      # target_num_samples: [0]
      # max_retrace_rays: [0]
      conserve_energy: True
      russian_roulette: False
      start_std: 0.0
      std_decay: 1.0
      cold_start_bg_iters: 0
      detach_N_iters: 0
      anoise: 0.25
      no_emitters: True
      no_diffuse: False
      freeze: False

      brdf_sampler:
        _target_: brdf_samplers.ggx.GGXSampler
        _partial_: True

      # brdf:
      #   _target_: modules.brdf.Specular
      #   _partial_: True
      #   lr: 1e-3
      #   bias: 0
      #   hidden_w: 64
      #   num_layers: 0

      brdf:
        _target_: modules.brdf.MLPBRDF
        _partial_: True
        mul_LdotN: True
        feape: 0
        dotpe: -1
        h_encoder:
          _target_: modules.ish.ListISH
          degs: [0,1,2,4]
        d_encoder:
          _target_: modules.ish.ListISH
          degs: [0,1,2,4]
        hidden_w: 64
        num_layers: 3
        initializer: 'kaiming'

        bias: 0
        activation: 'sigmoid'
        lr: 1e-3

      diffuse_module:
        _partial_: True
        _target_: modules.render_modules.RandHydraMLPDiffuse
        pospe: -1
        feape: 0
        # pospe: 12
        # feape: 0
        # view_encoder:
        #   _target_: modules.render_modules.PE
        #   max_degree: 2
        roughness_view_encoder: NULL
          # _target_: modules.render_modules.PE
          # max_degree: 2
        roughness_cfg:
          hidden_w: 64
          num_layers: 1
          # num_layers: 2
        hidden_w: 64
        num_layers: 1
        initializer: 'xavier_sigmoid'
        lr: 1e-3
        start_roughness: 0.35
        tint_bias: -1.1
        diffuse_bias: -0.619
        diffuse_mul: 1.5
        roughness_bias: -1
        # allocation: 7

      visibility_module: NULL
      # visibility_module:
        # _target_: modules.naive_vis_cache.NaiveVisCache
        # grid_size: 128
        # midpoint: 128
        # jump: 4

      bright_sampler:
        _target_: brdf_samplers.equirect_bright_sampler.ERBrightSampler

  bg_module:
    _target_: modules.integral_equirect.IntegralEquirect
    bg_resolution: 1024
    mipbias: 1
    activation: 'exp'
    lr: 0.02
    init_val: -0.6
    # init_val: -0.602
    mul_lr: 0
    brightness_lr: 0
    betas: [0.9, 0.99]
    mul_betas: [0.9, 0.9]
    mipbias_lr: 1e-4
    mipnoise: 0.0

  # bg_module:
  #   _target_: modules.dual_bg.MultiBG
  #   bgs: 
  #     - _target_: modules.integral_equirect.IntegralEquirect
  #       bg_resolution: 1024
  #       mipbias: 1
  #       activation: 'exp'
  #       lr: 0.02
  #       init_val: -0.6
  #       # init_val: -0.602
  #       mul_lr: 0
  #       brightness_lr: 0
  #       betas: [0.9, 0.99]
  #       mul_betas: [0.9, 0.9]
  #       mipbias_lr: 1e-4
  #       mipnoise: 0.0
  #
  #     - _target_: modules.integral_equirect.IntegralEquirect
  #       bg_resolution: 1024
  #       mipbias: 1
  #       activation: 'exp'
  #       lr: 0.02
  #       init_val: -0.6
  #       # init_val: -0.602
  #       mul_lr: 0
  #       brightness_lr: 0
  #       betas: [0.9, 0.99]
  #       mul_betas: [0.9, 0.9]
  #       mipbias_lr: 1e-4
  #       mipnoise: 0.0

  rf: 'placeholder'

params:
  L1_weight_initial: 8e-5
  L1_weight_rest: 4e-5
  clip_grad: Null
  weight_decay: 0
  eps: 1e-8
  betas: [0.9, 0.99]

  starting_batch_size: 100
  min_batch_size: 4096
  max_batch_size: 64000
  target_num_samples: 200000

  TV_weight_density: 0.0
  TV_weight_app: 0.0
  TV_weight_bg: 0
  envmap_lambda: 0
  pred_lambda: 3e-4
  final_pred_lambda: 3e-4
  diffuse_lambda: 0
  ori_lambda: 0.1
  final_ori_lambda: Null
  brdf_lambda: 0
  normal_err_lambda: 0
  
  distortion_lambda: 0 # 1e-3
  visibility_lambda: 0
  # distortion_lambda: 0.00001
  charbonier_eps: 1e-3
  ortho_weight: 0
  N_visibility_rays: 128

  n_iters: 30000
  charbonier_loss: false
  start_density: 5e-3
  batch_size: 4096
  lr: Null

  # configure decay
  lr_init: 1
  lr_final: 1e-3
  lr_delay_mult: 0.1
  lr_delay_steps: 100

  bg_col: 'white'
