_target_: models.tensor_nerf.TensorNeRF
_partial_: True

density_shift: -10
alphaMask_thres: 0.0001
distance_scale: 25
rayMarch_weight_thres: 0.0001
nEnvSamples: 0
fea2denseAct: 'softplus_shift'
# fea2denseAct: 'relu_shift'
max_recurs: 0
infinity_border: False
enable_alpha_mask: true

rf:
  _partial_: True
  _target_: models.tensoRF.TensorVMSplit
  density_n_comp: 24
  appearance_n_comp: 48
  app_dim: 48
  step_ratio: 0.5
  density_res_multi: 1
  contract_space: False
  # num_levels: 1
  hier_sizes: [1]

bg_module:
  # _target_: models.render_modules.BackgroundRender
  _target_: models.render_modules.HierarchicalBG
  bg_rank: 3
  num_levels: 3
  num_layers: 0
  unwrap_fn: 
    # _target_: models.render_modules.PanoUnwrap
    _target_: models.render_modules.CubeUnwrap
  # view_encoder:
  #   _target_: models.ish.ISH
  #   max_degree: 6
  # bg_resolution: [4096, 2048]
  bg_resolution: 256

diffuse_module:
  _partial_: True
  _target_: models.render_modules.MLPDiffuse
  pospe: 0
  feape: 2
  view_encoder:
    _target_: models.ish.FullISH
    max_degree: 4
  featureC: 128
  num_layers: 2

ref_module:
  _partial_: True
  _target_: models.render_modules.MLPRender_FP
  feape: 2
  view_encoder:
    _target_: models.ish.FullISH
    max_degree: 4
  # ref_encoder:
  #   _target_: models.ish.FullISH
  #   max_degree: 4
  ref_encoder:
    _target_: models.ish.RandISH
    # rand_n: 8
    rand_n: 32
    std: 5
  featureC: 128
  num_layers: 3

normal_module:
  _partial_: True
  _target_: models.render_modules.DeepMLPNormal
  pospe: 16
  featureC: 128
  num_layers: 4
