arch:
  _target_: models.tensor_nerf.TensorNeRF
  _partial_: True

  alphaMask_thres: 0.0001
  rayMarch_weight_thres: 0.0001
  nEnvSamples: 0
  max_recurs: 0
  infinity_border: False
  enable_alpha_mask: false
  appdim_noise_std: 0.0
  max_normal_similarity: 1.0
  max_floater_loss: 1
  
  rf: 'placeholder'

  sampler:
    # _target_: samplers.alphagrid.AlphaGridSampler
    # enable_alpha_mask: False
    # nEnvSamples: 0
    _target_: samplers.raymarch.Raymarcher

  tonemap:
    # _target_: models.tonemap.HDRTonemap
    # _target_: models.tonemap.LinearTonemap
    _target_: models.tonemap.SRGBTonemap

  bg_module:
    _target_: models.bg_modules.HierarchicalCubeMap
    bg_resolution: 1600
    num_levels: 7
    activation: 'softplus'
    power: 2
    stds: []
    # lr: 0.30
    lr: 0.05

  diffuse_module:
    _partial_: True
    _target_: models.render_modules.MLPDiffuse
    pospe: 0
    feape: 0
    # view_encoder:
    #   _target_: models.ish.FullISH
    #   max_degree: 4
    featureC: 128
    num_layers: 3

  ref_module:
    _partial_: True
    _target_: models.render_modules.MLPRender_FP
    feape: 0
    lr: 1e-4
    # view_encoder:
    #   _target_: models.ish.FullISH
    #   max_degree: 4
    ref_encoder:
      _target_: models.ish.ListISH
      degs: [0,1,2,4,8,16]
    # ref_encoder:
    #   _target_: models.render_modules.PE
    #   max_degree: 4
    # ref_encoder:
    #   _target_: models.ish.ISH
    #   max_degree: 6
    # ref_encoder:
    #   _target_: models.ish.RandISH
    #   rand_n: 64
    #   std: 5
    # activation: 'softplus'
    activation: 'sigmoid'
    featureC: 256
    num_layers: 8

  # normal_module:
  #   _partial_: True
  #   _target_: models.render_modules.DeepMLPNormal
  #   pospe: 16
  #   featureC: 128
  #   num_layers: 5
  #   lr: 1e-3
  normal_module:
    _partial_: True
    _target_: models.render_modules.MLPNormal
    lr: 3e-3
    pospe: 0
    feape: 0
    featureC: 128
    num_layers: 5

params:
  smoothing_start: 1.5
  smoothing_end: 1.5
  lambda_start: 0.0
  lambda_end: 0.0
  smoothing_list: [10000, 15000, 20000]
  N_voxel_init: 2097156 # 128**3
  N_voxel_final: 27000000 # 300**3
  # N_voxel_init: 27000000 # 128**3
  # N_voxel_final: 134217728 # 300**3

  # bounce_n_list: [100, 1000, 10000, 20000]
  # bounce_iter_list: [9000, 12000, 14000]

  bounce_n_list: [4000, 4000]
  bounce_iter_list: [0]

  num_bw_iters: 0

  # bg_upsamp_list: [300, 800, 1000, 3000]
  # bg_upsamp_res: [256, 512, 1024, 2048, 4096]
  # bg_upsamp_lr: [0.03, 0.015, 0.005, 0.003, 0.001]

  # bg_upsamp_list: [500, 1000, 2000, 3000]
  # bg_upsamp_res: [128, 512, 1024, 1024, 2048]
  # bg_upsamp_lr: [0.03, 0.03, 0.015, 0.015, 0.015]

  upsamp_list: [3000,4000,5500,7000]
  #upsamp_list: [2000,3000,4000,5500,7000]
  #uplambda_list: [7000, 12000, 17000, 21000]
  #uplambda_list: [7000, 12000, 17000]
  uplambda_list: [7000, 10000, 12000]
  update_AlphaMask_list: [4000, 7000]
  # update_AlphaMask_list: [30000]
  # L1_weight_inital: 8e-5
  # L1_weight_rest: 4e-5
  L1_weight_inital: 0
  L1_weight_rest: 0

  TV_weight_density: 0.0
  TV_weight_app: 0.0
  normal_lambda: 3e-4
  diffuse_lambda: 0
  backwards_rays_lambda: 1
  floater_lambda: 0.0001
  charbonier_eps: 0.001
  ortho_weight: 0

  envmap_train_start: 20
  # num_rays_per_envmap: 512
  num_rays_per_envmap: 64
  num_env_train_iters: 0
  n_iters: 30000
  charbonier_loss: false
  start_density: 1e-2
