arch:
  _target_: models.tensor_nerf.TensorNeRF
  _partial_: True

  alphaMask_thres: 0.0001
  rayMarch_weight_thres: 0.0001
  max_recurs: 2
  roughness_rays: 1
  infinity_border: False
  appdim_noise_std: 0.1
  world_bounces: 0
  max_normal_similarity: 0.99
  max_floater_loss: 1
  bounces_per_ray: 10
  selector:
    _target_: modules.pt_selectors.TopNWeight
    _partial_: True
    max_selected: 25000000
    weight_thres: 1e-3

  sampler:
    _target_: samplers.continuous_alphagrid.ContinuousAlphagrid
    _partial_: True
    multiplier: 1
    shrink_iters: [2000, 4000]
    dynamic_batchsize: False
    # sample_mode: multi_jitter
    sample_mode: single_jitter
    test_sample_mode: midpoint
    # threshold: 5e-5
    threshold: 1e-4
    grid_size: 256
    conv: 10
    bound: 1.5

  rf: "placeholder"

  tonemap:
    # _target_: models.tonemap.HDRTonemap
    # _target_: models.tonemap.LinearTonemap
    _target_: models.tonemap.SRGBTonemap

  # brdf:
  #   _target_: models.brdf.PBR
  #   _partial_: True

  # bg_module:
  #   _target_: models.bg_modules.HierarchicalCubeMap
  #   bg_resolution: 1024
  #   mipbias: -1
  #   num_levels: 1
  #   activation: 'softplus'
  #   power: 2
  #   stds: []
  #   # lr: 0.30
  #   lr: 0.025
  #   mipbias_lr: 1e-4
  #   # lr: 0.025

  ref_module:
    _partial_: True
    _target_: models.render_modules.MLPRender_FP
    feape: 0
    lr: 1e-4
    # view_encoder:
    #   _target_: models.ish.FullISH
    #   max_degree: 4
    # ref_encoder:
    #   _target_: models.ish.ListISH
    #   degs: [0,1,2,4,8,16]
    ref_encoder:
      _target_: modules.refsh.RefSH
      deg_view: 5
    # ref_encoder:
    #   _target_: models.render_modules.PE
    #   max_degree: 4
    # ref_encoder:
    #   _target_: models.ish.ISH
    #   max_degree: 6
    # ref_encoder:
    #   _target_: models.ish.RandISH
    #   rand_n: 64
    #   std: 5
    # activation: 'softplus'
    activation: 'sigmoid'
    featureC: 256
    num_layers: 8

  diffuse_module:
    _partial_: True
    _target_: models.render_modules.MLPDiffuse
    pospe: 0
    # feape: 2
    # featureC: 128
    feape: 0
    featureC: 64
    num_layers: 3
    lr: 1e-4
    diffuse_offset: -0.477
    tint_offset: 0

  normal_module:
    _partial_: True
    _target_: models.render_modules.MLPNormal
    lr: 1e-3
    # pospe: 16
    # feape: 2
    # featureC: 128
    pospe: 0
    feape: 0
    featureC: 64
    num_layers: 3

params:
  lambda_start: 0.0
  lambda_end: 0.0
  clip_grad: 1e-3
  eps: 1e-6
  betas: [0.9, 0.999]

  # bounce_n_list: [100, 1000, 10000, 20000]
  # bounce_iter_list: [9000, 12000, 14000]

  bounce_n_list: [0, 100000]
  # bounce_iter_list: [4500]
  bounce_iter_list: [0]

  num_bw_iters: 0

  #upsamp_list: [2000,3000,4000,5500,7000]
  #uplambda_list: [7000, 12000, 17000, 21000]
  #uplambda_list: [7000, 12000, 17000]
  uplambda_list: [7000, 10000, 12000]
  L1_weight_inital: 0
  L1_weight_rest: 0

  TV_weight_density: 0.0
  TV_weight_app: 0.0
  TV_weight_bg: 0
  envmap_lambda: 0
  brdf_lambda: 0
  pred_lambda: 3e-3
  final_pred_lambda: 3e-3
  diffuse_lambda: 0
  ori_lambda: 0.1
  final_ori_lambda: 0.1
  distortion_lambda: 0
  charbonier_eps: 1e-3
  ortho_weight: 0

  envmap_train_start: 20
  # num_rays_per_envmap: 512
  num_rays_per_envmap: 64
  num_env_train_iters: 0
  n_iters: 30000
  charbonier_loss: false
  start_density: 1e-3
  lr_init: 0.02
  batch_size: 4096
