_target_: models.tensor_nerf.TensorNeRF
_partial_: True

density_shift: -10
alphaMask_thres: 0.001
distance_scale: 25
rayMarch_weight_thres: 0.0001
nEnvSamples: 0
fea2denseAct: 'softplus_shift'
# fea2denseAct: 'softplus'
# fea2denseAct: 'relu_shift'
max_recurs: 0
enable_refraction: True
infinity_border: False
enable_alpha_mask: false

rf:
  _partial_: True
  _target_: models.tensoRF.TensorVMSplit
  density_n_comp: 16
  # appearance_n_comp: 48
  # app_dim: 48
  appearance_n_comp: 24
  app_dim: 27
  step_ratio: 0.5
  density_res_multi: 1
  contract_space: False
  # num_levels: 1
  hier_sizes: [1]

diffuse_module:
  _partial_: True
  _target_: models.render_modules.MLPDiffuse
  pospe: 0
  feape: 2
  view_encoder:
    _target_: models.ish.FullISH
    max_degree: 4
  featureC: 128
  num_layers: 5
