arch:
  _target_: models.tensor_nerf.TensorNeRF
  _partial_: True

  alphaMask_thres: 0.0001
  rayMarch_weight_thres: 0.0001
  attach_normal_iter: 000
  nEnvSamples: 0
  appdim_noise_std: 0
  max_recurs: 0
  infinity_border: False
  back_clip: 0.3

  tonemap:
    # _target_: models.tonemap.HDRTonemap
    _target_: models.tonemap.LinearTonemap
    # _target_: models.tonemap.SRGBTonemap

  sampler:
    _target_: samplers.continuous_alphagrid.ContinuousAlphagrid
    _partial_: True
    multiplier: 1
    shrink_iters: [2000, 4000]
    dynamic_batchsize: False
    sample_mode: single_jitter
    test_sample_mode: midpoint
    threshold: 1e-3
    grid_size: 128
    bound: 1.5

  diffuse_module:
    _partial_: True
    _target_: models.render_modules.MLPDiffuse
    # _target_: models.render_modules.MLPRender
    pospe: -1
    feape: 2
    view_encoder:
      _target_: models.render_modules.PE
      max_degree: 2
    featureC: 128
    num_layers: 3
    lr: 1e-3

  normal_module:
    _partial_: True
    _target_: models.render_modules.MLPNormal
    lr: 1e-3
    pospe: -1
    feape: 2
    # pospe: 12
    # feape: 0
    featureC: 128
    num_layers: 3
    # allocation: 3

  rf: 'placeholder'

params:
  L1_weight_inital: 8e-5
  L1_weight_rest: 4e-5

  TV_weight_density: 0.0
  TV_weight_app: 0.0
  normal_lambda: 3e-3
  diffuse_lambda: 0
  backwards_rays_lambda: 0.1
  floater_lambda: 0 #1e-4
  visibility_lambda: 0
  N_visibility_rays: 128
  # floater_lambda: 0.00001
  ortho_weight: 0

  n_iters: 30000
  charbonier_loss: false
  start_density: 1e-4
  lr_init: 0.02
  batch_size: 4096
