scenedir: nerf_synthetic/helmet_christmas
dataset_name: blender
downsample_train: 1
downsample_test: 1
ndc_ray: false
near_far: [3, 5]
stack_norms: false
gt_bg: christmas_photo_studio_04_4k.exr
aabb_scale: 2
