scenedir: nerf_synthetic/relighting/teapot_christmas
dataset_name: blender
downsample_train: 1
downsample_test: 1
ndc_ray: false
near_far: [3, 5]
aabb_scale: 1
gt_bg: christmas_photo_studio_04_4k.exr
