_partial_: True
# _target_: fields.tcnn.TCNNRF
_target_: fields.hashgrid.HashGridRF
distance_scale: 0.5
density_shift: 0
activation: 'exp'
# activation: 'softplus'
hidden_w: 64
num_layers: 4
# initializer: 'xavier'
enc_mul: 100
initializer: 'kaiming'
encoder_conf:
    n_levels: 16
    n_features_per_level: 2
    log2_hashmap_size: 19
    base_resolution: 16
    finest_resolution: 512
lr: 1e-3
lr_net: 1e-3
num_pretrain: 0
tint_offset: -1.1
diffuse_offset: -1.1
# app_dim: 16
enc_dim: 16

