_partial_: True
_target_: fields.hybrid.HybridRF
distance_scale: 1
density_shift: 0
activation: 'exp'
# activation: 'softplus'
hidden_w: 64
num_layers: 2
# initializer: 'xavier'
enc_mul: 1
initializer: 'kaiming'
encoder_conf:
    otype: "HashGrid"
    log2_hashmap_size: 19
lr: 1e-3
lr_net: 1e-3
lr_density: 1e-3
num_pretrain: 0
tint_offset: -1.1
diffuse_offset: -1.1
# app_dim: 16
enc_dim: 16

# tensorf params
n_levels: 0
grid_levels: 1
n_features_per_level: 8
base_resolution: 64
max_resolution: 64
# max_resolution: 128
#
TV_samples: 64
TV_scale: 0.5

# grid:
#     _target_: fields.tensoRF.TensoRF
#     _partial_: True
#     init_mode: 'randplane'
#     interp_mode: 'bilinear'
#     init_val: 0.01
#     lr: 2e-2
#     smoothing: 0.5
grid_conf:
    otype: "Grid"
    type: "Dense"
