hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - expname=ball_refnerf_grid_searchdensity
    - model=grid_mlp
    - dataset=ball
    - vis_every=10000
    - model.params.start_density=1e-2,1e-3,1e-4
    - render_test=False
  job:
    name: train
    chdir: null
    override_dirname: dataset=ball,expname=ball_refnerf_grid_searchdensity,model.params.start_density=1e-2,1e-3,1e-4,model=grid_mlp,render_test=False,vis_every=10000
    id: ???
    num: ???
    config_name: default
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.2.0
    version_base: '1.2'
    cwd: /home/amai/normalrf
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/amai/normalrf/configs
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      model: grid_mlp
      dataset: ball
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
render_mode: center
basedir: ./log
filter_rays: false
batch_size: 4096
expname: ball_refnerf_grid_searchdensity
datadir: /data
render_only: false
render_train: false
render_test: false
render_path: false
add_timestamp: false
nSamples: 1000000.0
N_vis: 5
vis_every: 10000
progress_refresh_rate: 10
rm_weight_mask_thre: 0.0001
step_ratio: 0.5
ckpt: null
lr_init: 0.01
lr_basis: 0.001
lr_decay_iters: -1
lr_decay_target_ratio: 0.1
lr_upsample_reset: 1
fp16: false
n_bg_iters: 1000
save_often: false
dataset:
  scenedir: nerf_synthetic/ball
  dataset_name: blender
  downsample_train: 1
  downsample_test: 1
  ndc_ray: false
  near_far:
  - 0.1
  - 6
model:
  arch:
    _target_: models.tensor_nerf.TensorNeRF
    _partial_: true
    density_shift: 0
    alphaMask_thres: 0.0001
    distance_scale: 25
    rayMarch_weight_thres: 0.0001
    nEnvSamples: 0
    fea2denseAct: softplus_shift
    max_recurs: 0
    infinity_border: false
    enable_alpha_mask: false
    appdim_noise_std: 0.1
    max_normal_similarity: 1.0
    tonemap:
      _target_: models.tonemap.SRGBTonemap
    rf:
      _partial_: true
      _target_: models.grid.Grid
      app_dim: 24
      step_ratio: 0.5
      density_res_multi: 1
      contract_space: false
      density_n_comp: 16
      appearance_n_comp: 24
    bg_module:
      _target_: models.bg_modules.HierarchicalCubeMap
      bg_resolution: 1600
      num_levels: 7
      activation: softplus
      power: 2
      stds: []
      lr: 0.05
    diffuse_module:
      _partial_: true
      _target_: models.render_modules.MLPDiffuse
      pospe: 0
      feape: 2
      featureC: 128
      num_layers: 3
    ref_module:
      _partial_: true
      _target_: models.render_modules.MLPRender_FP
      feape: 0
      lr: 0.0001
      ref_encoder:
        _target_: models.ish.ListISH
        degs:
        - 0
        - 1
        - 2
        - 4
        - 8
        - 16
      activation: sigmoid
      featureC: 256
      num_layers: 8
    normal_module:
      _partial_: true
      _target_: models.render_modules.MLPNormal
      lr: 0.003
      pospe: 16
      feape: 2
      featureC: 128
      num_layers: 5
  params:
    smoothing_start: 1.5
    smoothing_end: 1.5
    lambda_start: 0.0
    lambda_end: 0.0
    smoothing_list:
    - 10000
    - 15000
    - 20000
    N_voxel_init: 2097156
    N_voxel_final: 2097156
    bounce_n_list:
    - 4000
    - 4000
    bounce_iter_list:
    - 0
    num_bw_iters: 0
    upsamp_list:
    - 3000
    - 4000
    - 5500
    - 7000
    uplambda_list:
    - 7000
    - 10000
    - 12000
    update_AlphaMask_list:
    - 4000
    - 7000
    L1_weight_inital: 8.0e-05
    L1_weight_rest: 4.0e-05
    TV_weight_density: 0.0001
    TV_weight_app: 0
    normal_lambda: 0.0003
    diffuse_lambda: 0
    backwards_rays_lambda: 1
    floater_lambda: 0.0001
    charbonier_eps: 0.001
    ortho_weight: 0
    envmap_train_start: 20
    num_rays_per_envmap: 64
    num_env_train_iters: 0
    n_iters: 30000
    charbonier_loss: false
    start_density: 0.01
    lr_init: 0.2
