n_iters: 60000
render_mode: center

N_voxel_init: 2097156 # 128**3
N_voxel_final: 27000000 # 300**3

tensorf:
  _target_: models.tensor_nerf.TensorNeRF
  _partial_: True

  density_shift: -10
  alphaMask_thres: 0.0001
  distance_scale: 25
  rayMarch_weight_thres: 0.0001
  nEnvSamples: 100
  fea2denseAct: 'softplus_shift'
  bundle_size: 1
  rf:
    _partial_: True
    _target_: models.tensoRF.TensorVMSplit
    density_n_comp: 16
    appearance_n_comp: 36
    app_dim: 27
    step_ratio: 0.5
    density_res_multi: 1
    nEnvSamples: 0
    contract_space: True
    infinity_border: True
    num_levels: 1
    hier_sizes: [1]
  diffuse_module:
    _target_: models.render_modules.MLPDiffuse
    in_channels: 27
    viewpe: 0
    feape: 2
    featureC: 128
    num_layers: 0
  ref_module:
    _target_: models.render_modules.MLPRender_FP
    in_channels: 27
    viewpe: 0
    feape: 2
    refpe: 6
    featureC: 128
    num_layers: 4
  normal_module:
    _target_: models.render_modules.MLPNormal
    in_channels: 27
    pospe: 6
    feape: 2
    featureC: 128
    num_layers: 1
  # bg_module:
  #   _target_: models.render_modules.BackgroundRender
  #   bg_rank: 8
    # bg_resolution: [1024, 512]

#featureC: 256
#N_voxel_init: 262144 # 64**3
#N_voxel_final: 47000000 # 300**3

scheduling:
  smoothing_start: 1.0
  smoothing_end: 0.5

  bounce_n_list: [100, 1000, 10000, 20000]
  bounce_iter_list: [9000, 12000, 14000]


  upsamp_list: [3000,4000,5500,7000]
  #upsamp_list: [2000,3000,4000,5500,7000]
  #uplambda_list: [7000, 12000, 17000, 21000]
  #uplambda_list: [7000, 12000, 17000]
  uplambda_list: [7000, 10000, 12000]
  update_AlphaMask_list: [4000,10000]
  # update_AlphaMask_list: [30000]

N_vis: 5
vis_every: 5000

pos_pe: 6
view_pe: 3
ref_pe: 6
fea_pe: 2

L1_weight_inital: 8e-5
L1_weight_rest: 4e-5
rm_weight_mask_thre: 1e-4